name: release

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.event.after }}
  cancel-in-progress: true

jobs:
  build:
    name: Build static retsnoop binary
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - arch: amd64
            file_str: x86-64
            target: x86_64-unknown-linux-gnu

    steps:
      # amd64 needs the dependencies to build retsnoop
      - name: (amd64) Install dependencies
        if: matrix.arch == 'amd64'
        run: |
          sudo apt-get update
          sudo apt-get install -y cargo llvm libelf-dev

      - name: Checkout retsnoop code
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          submodules: recursive
          path: 'retsnoop'

      - name: Tests for LLVM
        working-directory: 'retsnoop'
        run: |
          printf '%b\n' '#include <llvm-c/Core.h>\n' '#include <llvm-c/TargetMachine.h>\n' 'int main(void) {' '	char *triple = LLVMNormalizeTargetTriple("");' '	LLVMDisposeMessage(triple);' '	return 0;' '}' | cc  -I/usr/lib/llvm-14/include  -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS  -L/usr/lib/llvm-14/lib  -Wall -Werror -x c - -lLLVM-14 -o /tmp/test-llvm || true
          ls -l /lib/x86_64-linux-gnu/libLLVM* || true
          ldd /tmp/test-llvm || true

      - name: (amd64) Build static retsnoop natively
        if: matrix.arch == 'amd64'
        working-directory: 'retsnoop'
        run: |
          CFLAGS=--static \
              make -j -C src V=1 || true

          sudo apt-get install llvm-dev
          printf '%b\n' '#include <llvm-c/Core.h>\n' '#include <llvm-c/TargetMachine.h>\n' 'int main(void) {' '	char *triple = LLVMNormalizeTargetTriple("");' '	LLVMDisposeMessage(triple);' '	return 0;' '}' | cc  -I/usr/lib/llvm-14/include  -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS  -L/usr/lib/llvm-14/lib  -Wall -Werror -x c - -lLLVM-14 -o /tmp/test-llvm || true
          ls -l /lib/x86_64-linux-gnu/libLLVM* || true
          ldd /tmp/test-llvm || true
          CFLAGS=--static \
              make -j -C src V=1 || true

          strip src/retsnoop

      - name: Test retsnoop binary
        working-directory: 'retsnoop/src'
        run: |
          file ./retsnoop | \
              tee /dev/stderr | \
              grep -q "${{ matrix.file_str }}"
          ./retsnoop --usage | grep -q Usage
          ldd ./retsnoop 2>&1 | \
              tee /dev/stderr | \
              grep -q 'not a dynamic executable'
